# Generated by Django 5.1.3 on 2025-02-01 00:39

import apps.funcionario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='funcionarios_fotos/')),
                ('data_admissao', models.DateField(default=apps.funcionario.models.Funcionario.current_date)),
                ('entrada', models.TimeField()),
                ('saida', models.TimeField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cref', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
    ]
