# Generated by Django 5.1.3 on 2024-12-11 19:21

import apps.funcionario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0004_alter_funcionario_data_admissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(default=apps.funcionario.models.Funcionario.current_date),
        ),
    ]
