# Generated by Django 5.1.3 on 2024-12-23 01:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('cadastro', 'Cadastro'), ('assinatura', 'Assinatura'), ('inscrição', 'Instrição em aula'), ('atualização', 'Atualização de Dados'), ('exclusão', 'Cancelamento de Aula')], max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Registro de Atividade',
                'verbose_name_plural': 'Registros de Atividades',
                'ordering': ['-data_hora'],
            },
        ),
    ]
