# Generated by Django 5.1.3 on 2024-12-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='tipo_acao',
            field=models.CharField(choices=[('cadastro', 'Cadastro'), ('assinatura', 'Assinatura de Plano'), ('inscricao', 'Inscrição em aula'), ('atualizacao', 'Atualização de Dados'), ('exclusao', 'Exclusão de Dados')], max_length=20),
        ),
    ]
