# Generated by Django 5.1.3 on 2024-11-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='status',
            new_name='ativo',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='data_inscricao',
        ),
    ]
