# Generated by Django 5.1.3 on 2024-11-27 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='aluno',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='responsavel',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='first_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='last_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='first_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='last_name',
            field=models.CharField(max_length=256),
        ),
        migrations.CreateModel(
            name='AvaliacaoFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateField(auto_now_add=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_fisicas', to='aluno.aluno')),
            ],
        ),
    ]
