# Generated by Django 5.1.3 on 2024-11-27 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_alter_aluno_managers_alter_responsavel_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='responsavel',
            name='user_permissions',
        ),
    ]
