# Generated by Django 5.1.3 on 2024-11-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_remove_aluno_groups_remove_aluno_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaofisica',
            name='circunferencia_abdominal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='avaliacaofisica',
            name='gordura_corporal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='avaliacaofisica',
            name='massa_muscular',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
