# Generated by Django 5.1.3 on 2025-02-27 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_remove_aluno_responsavel_delete_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_admissao',
            field=models.DateField(default=datetime.date(2025, 2, 27)),
        ),
    ]
