# Generated by Django 5.1.3 on 2025-03-04 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0006_aluno_data_admissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_admissao',
            field=models.DateField(default=datetime.date(2025, 3, 4)),
        ),
    ]
