# Generated by Django 5.1.3 on 2024-12-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='aulas',
            field=models.BooleanField(default=False),
        ),
    ]
