# Generated by Django 5.1.3 on 2025-02-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0003_alter_assinatura_data_assinatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('musculacao', 'Musculação e Treinamento de Força'), ('cardio', 'Treinamento Cardiovascular'), ('aulas_coletivas', 'Aulas Coletivas'), ('funcional', 'Treinamento Funcional'), ('artes_marciais', 'Artes Marciais e Defesa Pessoal'), ('yoga_alongamento', 'Yoga e Alongamento'), ('aquaticas', 'Atividades Aquáticas'), ('treino_especifico', 'Treinos Específicos')], max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
