# Generated by Django 5.1.3 on 2025-02-03 00:12

from django.db import migrations

def criar_atividades(apps, schema_editor):
    AtividadeExtra = apps.get_model("plano", "AtividadeExtra")

    atividades_em_ordem = [
        ('aulas_coletivas', 'Aulas Coletivas'),
        ('funcional', 'Treinamento Funcional'),
        ('artes_marciais', 'Artes Marciais e Defesa Pessoal'),
        ('yoga_alongamento', 'Yoga e Alongamento'),

    ]

    for tipo, nome in atividades_em_ordem:
        AtividadeExtra.objects.get_or_create(nome=tipo, defaults={"descricao": nome})


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0004_atividadeextra'),
    ]

    operations = [
        migrations.RunPython(criar_atividades)
    ]
