# Generated by Django 5.1.3 on 2025-02-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0005_auto_20250202_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='aulas',
        ),
        migrations.AddField(
            model_name='plano',
            name='atividade_extra',
            field=models.ManyToManyField(blank=True, to='plano.atividadeextra'),
        ),
    ]
