# Generated by Django 5.1.3 on 2024-11-15 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('vagas', models.PositiveIntegerField(default=0)),
                ('horario_inicial', models.TimeField()),
                ('horario_final', models.TimeField()),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.CreateModel(
            name='Inscrição',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Inscrições',
            },
        ),
    ]
