# Generated by Django 5.1.3 on 2025-03-04 16:07

import apps.aula.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0001_initial'),
        ('plano', '0007_alter_atividadeextra_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('vagas', models.PositiveIntegerField(default=1)),
                ('horario_inicial', models.TimeField()),
                ('horario_final', models.TimeField()),
                ('instrutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionario.funcionario')),
                ('tipo_atividade', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plano.atividadeextra')),
                ('dias_da_semana', models.ManyToManyField(to='aula.diasemana')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.CreateModel(
            name='Inscrição',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateField(default=apps.aula.models.Inscrição.current_date)),
                ('assinatura', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='plano.assinatura')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.aula')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('aula', 'assinatura'), name='unique_aula_assinatura', violation_error_message='Esta assinatura já está inscrita na aula!!!')],
            },
        ),
    ]
