# Generated by Django 5.1.3 on 2024-11-26 00:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
        ('funcionario', '0002_alter_instrutor_funcionario_ptr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('vagas', models.PositiveIntegerField(default=1)),
                ('horario_inicial', models.TimeField()),
                ('horario_final', models.TimeField()),
                ('instrutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionario.instrutor')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.CreateModel(
            name='Inscrição',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateField(default=django.utils.timezone.now)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.aula')),
            ],
            options={
                'verbose_name': 'Inscricoes',
            },
        ),
    ]
