# Generated by Django 5.1.3 on 2025-03-04 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
        ('plano', '0007_alter_atividadeextra_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrição',
            name='assinatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano.assinatura'),
        ),
    ]
