# Generated by Django 5.1.3 on 2025-02-03 00:10

from django.db import migrations

def criar_atividades(apps, schema_editor):
    DiaSemana = apps.get_model("aula", "DiaSemana")

    dias_em_ordem = [
        ('SEG', 'Segunda-feira'),
        ('TER', 'Terça-feira'),
        ('QUA', 'Quarta-feira'),
        ('QUI', 'Quinta-feira'),
        ('SEX', 'Sexta-feira'),
        ('SAB', 'Sábado'),
        ('DOM', 'Domingo'),
    ]

    for tipo, nome in dias_em_ordem:
        DiaSemana.objects.get_or_create(nome=tipo)

class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(criar_atividades)
    ]
