# Generated by Django 5.1.3 on 2024-11-15 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
        ('aula', '0001_initial'),
        ('instrutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='instrutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instrutor.instrutor'),
        ),
        migrations.AddField(
            model_name='inscrição',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno'),
        ),
        migrations.AddField(
            model_name='inscrição',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.aula'),
        ),
    ]
