# Generated by Django 5.1.3 on 2024-11-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscrição',
            options={'verbose_name': 'Inscricoes'},
        ),
    ]
