# Generated by Django 5.1.3 on 2025-02-03 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_auto_20250202_2110'),
        ('plano', '0007_alter_atividadeextra_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='tipo_atividade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='plano.atividadeextra'),
        ),
    ]
