# Generated by Django 5.1.3 on 2024-12-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_diasemana_aula_dias_da_semana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='dias_da_semana',
        ),
        migrations.DeleteModel(
            name='DiaSemana',
        ),
        migrations.AddField(
            model_name='aula',
            name='dias_da_semana',
            field=models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], default=1, max_length=24),
            preserve_default=False,
        ),
    ]
