# Generated by Django 5.1.3 on 2025-03-06 00:10

from django.db import migrations

def criar_dias(apps, schema_editor):
    Model = apps.get_model("aula", "DiaSemana")

    DIAS_CHOICES = [
        ('SEG', 'Segunda-feira'),
        ('TER', 'Terça-feira'),
        ('QUA', 'Quarta-feira'),
        ('QUI', 'Quinta-feira'),
        ('SEX', 'Sexta-feira'),
        ('SAB', 'Sábado'),
        ('DOM', 'Domingo'),
    ]

    for tipo, nome in DIAS_CHOICES:
        Model.objects.get_or_create(nome=tipo)

class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_alter_inscrição_assinatura'),
    ]

    operations = [
        migrations.RunPython(criar_dias)
    ]
