# Generated by Django 5.1.3 on 2025-02-27 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0003_aula_tipo_atividade'),
        ('plano', '0007_alter_atividadeextra_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='tipo_atividade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plano.atividadeextra'),
        ),
    ]
