# Generated by Django 5.1.3 on 2024-12-17 01:44

import apps.aula.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_avaliacaofisica_circunferencia_abdominal_and_more'),
        ('aula', '0004_diasemana_remove_aula_dias_da_semana_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscrição',
            options={},
        ),
        migrations.AlterField(
            model_name='inscrição',
            name='data_inscricao',
            field=models.DateField(default=apps.aula.models.Inscrição.current_date),
        ),
        migrations.AlterUniqueTogether(
            name='inscrição',
            unique_together={('aluno', 'aula')},
        ),
    ]
